import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Link from "next/link";
import SessionWrapper from "./SessionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <body id="root-app" className="min-h-screen bg-gradient-to-br from-blue-100 via-white to-pink-100">
        <SessionWrapper>
          <header className="w-full shadow bg-white/80 backdrop-blur sticky top-0 z-10">
            <nav className="container mx-auto flex items-center justify-between py-4 px-4">
              <div className="flex items-center space-x-2">
                <span className="text-2xl font-extrabold text-blue-600 tracking-tight">NextAuthTest</span>
              </div>
              <div className="flex space-x-4">
                <Link href="/" className="text-gray-700 hover:text-blue-600 font-medium transition">Accueil</Link>
                <Link href="/register" className="text-gray-700 hover:text-blue-600 font-medium transition">Inscription</Link>
                <Link href="/login" className="text-gray-700 hover:text-blue-600 font-medium transition">Connexion</Link>
                <Link href="/profile" className="text-gray-700 hover:text-blue-600 font-medium transition">Profil</Link>
              </div>
            </nav>
          </header>
          <main className="container mx-auto py-8 px-4 min-h-[80vh] flex flex-col items-center justify-center">
        {children}
          </main>
        </SessionWrapper>
      </body>
    </html>
  );
}
